name: my-scrapper
version: 0.1.0.0
github: "githubuser/my-scrapper"
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2021 Author name here"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/my-scrapper#readme>

dependencies:
  - base >= 4.7 && < 5
  - bytestring >=0.10 && <0.11
  - text >=0.11 && <2.0
  - http-client >=0.3 && <0.4
  # - http-conduit >=2.3 && <2.4

# extra-deps:

library:
  source-dirs: src

executables:
  my-scrapper-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - my-scrapper
# tests:
#   my-scrapper-test:
#     main: Spec.hs
#     source-dirs: test
#     ghc-options:
#       - -threaded
#       - -rtsopts
#       - -with-rtsopts=-N
#     dependencies:
#       - my-scrapper
